---
title: "Understanding the Changing Patterns of Human Mobility in Britain During the COVID19 Pandemic through Facebook Data - Mobility Indicators"
author: "Alessia Calafiore"
date: "11/18/2021"
---

# Exploring Facebook mobility data
  
```{r}
library(sf)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(ggpubr)

grid<-st_read("~/itinerant/grid_final/grid_w_classes_poly.gpkg")

files<-list.files("~/itinerant/pre-processed-movements/exploration/selected_dates",full.names = T) ###files of the two months have been manually moved to a specific folder 
df<-files %>% purrr::map_dfr(~ readRDS(.x))

period_1=df[df$date<"2021-01-01",]
period_2=df[df$date>"2021-01-01",] 

```

## Outflows

```{r}

outflows1<-period_1 %>%
  filter(length_km != 0) %>%
  group_by(start_polygon_name,origin_class) %>%
  summarise(
    median_out=median(n_crisis,na.rm=T),
    median_out_b=median(n_baseline,na.rm=T),
    ratio=median_out/median_out_b
  )%>%
  mutate(
  origin_class=factor(origin_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
  time_interval="Lockdown")

outflows2<-period_2 %>%
  filter(length_km != 0) %>%
  group_by(start_polygon_name,origin_class) %>%
  summarise(
    median_out=median(n_crisis,na.rm=T),
    median_out_b=median(n_baseline,na.rm=T),
    ratio=median_out/median_out_b
  )%>%
  mutate(
  origin_class=factor(origin_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
  time_interval="Restictions Lifted")

outflows<-rbind(outflows1,outflows2)
  
```

## Inflows

```{r}

inflows1<-period_1 %>%
  filter(length_km != 0) %>%
  group_by(end_polygon_name,destination_class) %>%
  summarise(
    median_in=median(n_crisis,na.rm=T),
    median_in_b=median(n_baseline,na.rm=T),
    ratio=median_in/median_in_b
  )%>%
  mutate(
  destination_class=factor(destination_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
  time_interval="Lockdown")

inflows2<-period_2 %>%
  filter(length_km != 0) %>%
  group_by(end_polygon_name,destination_class) %>%
  summarise(
    median_in=median(n_crisis,na.rm=T),
    median_in_b=median(n_baseline,na.rm=T),
    ratio=median_in/median_in_b
  )%>%
  mutate(
  destination_class=factor(destination_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
  time_interval="Restictions Lifted")

inflows<-rbind(inflows1,inflows2)

```

## Intramobility

```{r}
intra1<-period_1 %>%
  filter(length_km == 0) %>%
  group_by(end_polygon_name,destination_class) %>%
  summarise(
    median_in=median(n_crisis,na.rm=T),
    median_in_b=median(n_baseline,na.rm=T),
    ratio=median_in/median_in_b
  )%>%
  mutate(
  destination_class=factor(destination_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
  time_interval="Lockdown")

intra2<-period_2 %>%
  filter(length_km == 0) %>%
  group_by(end_polygon_name,destination_class) %>%
  summarise(
    median_in=median(n_crisis,na.rm=T),
    median_in_b=median(n_baseline,na.rm=T),
    ratio=median_in/median_in_b
  )%>%
  mutate(
  destination_class=factor(destination_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
  time_interval="Restictions Lifted")

intraMov<-rbind(intra1,intra2)
```

## Net mobility

```{r}
net_mob<-full_join(outflows,inflows,by=c("start_polygon_name"="end_polygon_name","origin_class"="destination_class"))%>%
  replace(is.na(.), 0)%>%
  mutate(
    net_ratio_1=ratio.x.y-ratio.x.x, #outflows ratio-inflows ratio
    net_ratio_2=ratio.y.y-ratio.y.x
  )%>%
  select(start_polygon_name,origin_class,net_ratio_1,net_ratio_2)%>%
  pivot_longer(starts_with("net_"),names_to = "time_interval",values_to = "net_ratio")

```

## Viz

```{r}

out<-ggplot(outflows,aes(x=origin_class,y=(ratio-1)*100, color=origin_class,fill=origin_class,group=origin_class))+
  geom_boxplot(varwidth = TRUE,alpha=0.2)+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  theme_bw()+
  ylim(-50,50)+
  theme(legend.position = "none")+
  labs(y="Outflows Change from Baseline (%) ",x="Population Class")+
  facet_wrap(~time_interval)

theme_tufte2 <- function(...) {
theme_tufte() +
theme(
text = element_text(family = "robotocondensed")
)
}

# load font
font_add_google("Roboto Condensed", "robotocondensed")
# automatically use showtext to render text


out<-ggplot(data = outflows, aes(x=origin_class,y=(ratio-1)*100, color=origin_class,fill=origin_class)) +
              scale_fill_viridis_d( option = "D") +
              scale_color_viridis_d( option = "D") +
              geom_hline(aes(yintercept = 0),color="gray")+
              geom_violin(alpha=0.4, position = position_dodge( width = .75 ), size = 0.5) +
              geom_boxplot(notch = TRUE, outlier.size = -1, width = 0.5, alpha = 0.5, color="black",size=0.2) +
              geom_point(shape = 21, size = 0.2, position = position_jitterdodge( ), alpha = 1,color="black") +
              theme_tufte() +
              theme(legend.position = "none",
              axis.text = element_text(size = 16),
              axis.title=element_text(size=18),
              strip.text = element_text(size=18)
              ) +
  ylim(-100,100)+
              labs(y="Outflows Change from Baseline (%) ",x="Population Class")+
                facet_wrap(~time_interval)

out
ggsave("~/itinerant/img/class_analysis/outflows.jpg",height=15, width=30, units="cm",bg="white",dpi=300)

inf<-ggplot(data = inflows, aes(x=destination_class,y=(ratio-1)*100, color=destination_class,fill=destination_class)) +
              scale_fill_viridis_d( option = "D") +
              scale_color_viridis_d( option = "D") +
              geom_hline(aes(yintercept = 0),color="gray")+
              geom_violin(alpha=0.4, position = position_dodge( width = .75 ), size = 0.5) +
              geom_boxplot(notch = TRUE, outlier.size = -1, width = 0.5, alpha = 0.5, color="black",size=0.2) +
              geom_point(shape = 21, size = 0.2, position = position_jitterdodge( ), alpha = 1,color="black") +
              theme_tufte() +
              theme(legend.position = "none",
              axis.text = element_text(size = 16),
              axis.title=element_text(size=18),
              strip.text = element_text(size=18)
              ) +
  ylim(-100,100)+
              labs(y="Inflows Change from Baseline (%) ",x="Population Class")+
                facet_wrap(~time_interval)
inf
ggsave("~/itinerant/img/class_analysis/inflows.jpg",height=15, width=30, units="cm",bg="white",dpi=300)

intra<-ggplot(data = intraMov, aes(x=destination_class,y=(ratio-1)*100, color=destination_class,fill=destination_class)) +
              scale_fill_viridis_d( option = "D") +
              scale_color_viridis_d( option = "D") +
              geom_hline(aes(yintercept = 0),color="gray")+
              geom_violin(alpha=0.4, position = position_dodge( width = .75 ), size = 0.5) +
              geom_boxplot(notch = TRUE, outlier.size = -1, width = 0.5, alpha = 0.5, color="black",size=0.2) +
              geom_point(shape = 21, size = 0.2, position = position_jitterdodge( ), alpha = 1,color="black") +
              theme_tufte() +
              theme(legend.position = "none",
              axis.text = element_text(size = 16),
              axis.title=element_text(size=18),
              strip.text = element_text(size=18)
              ) +
  ylim(-25,100)+
  labs(y="Intraflows Change from Baseline (%) ",x="Population Class")+
  facet_wrap(~time_interval)

intra
ggsave("~/itinerant/img/class_analysis/intra.jpg",height=15, width=30, units="cm",bg="white",dpi=300)
```

## Heatmap

```{r}
period_1_agg<-period_1 %>%
  group_by(origin_class,destination_class)%>%
  summarise(
    n_crisis=mean(n_crisis,na.rm = T),
    n_baseline=mean(n_baseline,na.rm = T)
  ) %>%
  mutate(
    ratio=n_crisis/n_baseline,
    same=ifelse(origin_class==destination_class,TRUE,FALSE),
    destination_class=factor(destination_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
    origin_class=factor(origin_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
    time_interval="Lockdown"
  )

period_1_agg%>%
  filter(same==FALSE)%>%
  ggplot(aes(x=origin_class,y=destination_class,fill=(ratio-1)*100))+
  geom_tile()+
  theme_bw()+
  scale_fill_viridis_c(direction = 1)+
  labs(x="Population Class (Origin)",y="Population Class (Destination)",fill="Movements Change \n from Baseline (%)")

ggsave("~/itinerant/img/class_analysis/heatmap.jpeg")

period_2_agg<-period_2 %>%
  group_by(origin_class,destination_class)%>%
  summarise(
    n_crisis=mean(n_crisis,na.rm = T),
    n_baseline=mean(n_baseline,na.rm = T)
  ) %>%
  mutate(
    ratio=n_crisis/n_baseline,
    same=ifelse(origin_class==destination_class,TRUE,FALSE),
    destination_class=factor(destination_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
    origin_class=factor(origin_class,levels = c("1","2","3","4","5","6","7","8","9","10")),
    time_interval="Restrictions Lifted"
  )

period_2_agg%>%
  filter(same==FALSE)%>%
  ggplot(aes(x=origin_class,y=destination_class,fill=(ratio-1)*100))+
  geom_tile()+
  theme_bw()+
  scale_fill_viridis_c(direction = 1)+
  labs(x="Population Class (Origin)",y="Population Class (Destination)",fill="Movements Change \n from Baseline (%)")

ggsave("~/itinerant/img/class_analysis/heatmap2.jpeg")

period_agg<-rbind(period_1_agg,period_2_agg)

period_agg%>%
  filter(same==FALSE)%>%
  ggplot(aes(x=origin_class,y=destination_class,fill=(ratio-1)*100))+
  geom_tile()+
  theme_bw()+
  scale_fill_viridis_c(direction = 1)+
  labs(x="Population Class (Origin)",y="Population Class (Destination)",fill="Movements Change \n from Baseline (%)")+
  facet_wrap(~time_interval)

ggsave("~/itinerant/img/class_analysis/heatmap.jpeg")
```

## Net flows Viz 

```{r}
netflows1<-outflows1 %>% 
  full_join(inflows1, by=c("origin_class"="destination_class","start_polygon_name"="end_polygon_name"))%>%
  select(start_polygon_name,origin_class,median_out,median_out_b,median_in,median_in_b)%>%
  replace(is.na(.), 0)%>%
    mutate(
      netflows=median_out-median_in,
      netflows_baseline=median_out_b-median_in_b
    )%>%
  mutate(
    time_interval="Lockdown"
  )

netflows2<-outflows2 %>% 
  full_join(inflows2, by=c("origin_class"="destination_class","start_polygon_name"="end_polygon_name"))%>%
  select(start_polygon_name,origin_class,median_out,median_out_b,median_in,median_in_b)%>%
  replace(is.na(.), 0)%>%
    mutate(
      netflows=median_out-median_in,
      netflows_baseline=median_out_b-median_in_b
    )%>%
  mutate(
    time_interval="Restrictions Lifted"
  )

netflows=rbind(netflows1,netflows2)
netflows<-netflows %>%
  pivot_longer(starts_with("net"),names_to = "type",values_to = "net_val")  

ggplot(netflows,aes(x=origin_class,y=net_val, color=origin_class,fill=origin_class,group=origin_class))+
  geom_boxplot(varwidth = TRUE,alpha=0.2)+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  theme_bw()+
  theme(legend.position = "none")+
  labs(y="Netflows (Out - In)",x="Population Class")+
  ylim(-50,+50)+
  facet_wrap(~time_interval+type)  

ggsave("~/itinerant/img/class_analysis/net.jpeg")

###Ratio

Population<-grid %>%
  st_drop_geometry()%>%
  group_by(class,polygon_name)%>%
  summarise(pop=sum(Population,na.rm=T))

netflows<-netflows %>%
  inner_join(Population,by=c("start_polygon_name"="polygon_name","origin_class"="class"))

netflows<-netflows %>%
  mutate(ratio=net_val/pop)

ggplot(netflows,aes(x=origin_class,y=ratio*10000, color=origin_class,fill=origin_class,group=origin_class))+
  geom_boxplot(varwidth = TRUE,alpha=0.2)+
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  theme_bw()+
  theme(legend.position = "none")+
  labs(y="Netflows for 10000 inh",x="Population Class")+
  ylim(-10,+10)+
  facet_wrap(~time_interval+type)  

ggsave("~/itinerant/img/class_analysis/net.jpeg")
```






